return {
    SANITY_RATE = 2,
    SANITY_MOVING_MULTIPLIER = 2,
    HEALTH_RATE = 5,
    HEALTH_DROP_POINT = 1.5,
    HEALTH_RANDOM_DROP_POINT = 1.02,
    HEALTH_DROP_STOP_POINT = 0.6,
    HEALTH_CURE_POINT = 0.4,
    HEALTH_HURT_COUNT = 5,
    HUNGER_MOVING_MULTIPLIER = 1,
    SPEED_SANITY_MULTIPLIER_MIN = 0.5,
}
