return {
    SANITY_RATE = 5,
    SANITY_MOVING_MULTIPLIER = 2,
    HEALTH_RATE = 1,
    HEALTH_DROP_POINT = 1.2,
    HEALTH_RANDOM_DROP_POINT = 1.02,
    HEALTH_DROP_STOP_POINT = 0.6,
    HEALTH_CURE_POINT = 0.01,
    HEALTH_HURT_COUNT = 3,
    HUNGER_MOVING_MULTIPLIER = 0.9,
    SPEED_SANITY_MULTIPLIER_MIN = 0.2,
}
