return {
    SANITY_RATE = 0,
    SANITY_MOVING_MULTIPLIER = 0,
    HEALTH_RATE = 20,
    HEALTH_DROP_POINT = 1.1,
    HEALTH_RANDOM_DROP_POINT = 1,
    HEALTH_DROP_STOP_POINT = -0.01,
    HEALTH_CURE_POINT = -0.1,
    HEALTH_HURT_COUNT = 1,
    HUNGER_MOVING_MULTIPLIER = 1,
    BASIC_MASS = 100,
    SPEED_SANITY_MULTIPLIER_MIN = 1,
}
