return {
    SANITY_RATE = 1.5,
    SANITY_MOVING_MULTIPLIER = 1.8,
    HEALTH_RATE = 0.3,
    HEALTH_DROP_POINT = 1.5,
    HEALTH_RANDOM_DROP_POINT = 1.05,
    HEALTH_DROP_STOP_POINT = 0.8,
    HEALTH_CURE_POINT = 0.6,
    HEALTH_HURT_COUNT = 8,
    HUNGER_MOVING_MULTIPLIER = 1.05,
    SPEED_SANITY_MULTIPLIER_MIN = 0.5,
}
