return {
    SANITY_RATE = 1,
    SANITY_MOVING_MULTIPLIER = 1.2,
    HEALTH_RATE = 0.1,
    HEALTH_DROP_POINT = 1.5,
    HEALTH_RANDOM_DROP_POINT = 1.2,
    HEALTH_DROP_STOP_POINT = 0.9,
    HEALTH_CURE_POINT = 0.8,
    HEALTH_HURT_COUNT = 10,
    HUNGER_MOVING_MULTIPLIER = 1.2,
    BASIC_MASS = 1,
    SPEED_SANITY_MULTIPLIER_MIN = 0.8,
}
